name: Daily Report Analysis

on:
  schedule:
    - cron: '10 23 * * *' # 한국 시간 오전 8시 10분 자동 실행
  workflow_dispatch: # 지금 바로 실행하는 버튼 만들기

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 google-generativeai
      - name: Run Crawler
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python crawler_py_for_github.py
